services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Derhansen\PwdSecurityCheck\:
        resource: '../Classes/*'

    Derhansen\PwdSecurityCheck\Command\ProcessCommand:
        tags:
            - name: 'console.command'
              command: 'pwd_security_check:process'
              schedulable: true
